/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'voi' at '5/10/16 3:32 PM' with Gradle 2.2.1
 *
 * @author voi, @date 5/10/16 3:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
